name: Build And Publish to NPM
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libblas-dev libopenblas-dev

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build with Make
        run: cmake --build build

      - name: Upload C++ build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build
          path: build/

  build-gyp:
    needs: [build-cpp]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Download C++ build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cpp-build
          path: build/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install build tools (for node-gyp)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 g++ make

      - name: Install dependencies and build node addon
        run: |
          cd node-audio-stem
          npm install
          node-gyp configure build

      - name: Upload node module artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-addon
          path: node-audio-stem/build/

  publish:
    needs: [build-gyp]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Download node addon build output
        uses: actions/download-artifact@v4
        with:
          name: node-addon
          path: node-audio-stem/build/

      - name: Publish to npm
        run: |
          cd node-audio-stem
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

          npm ci
          npm publish --provenance --access public
